CREATE TABLE IF NOT EXISTS eventTasks(
    id UUID PRIMARY KEY NOT NULL,
    eventId UUID NOT NULL,
    FOREIGN KEY (eventId) REFERENCES events (id) ON DELETE CASCADE,
    description TEXT NOT NULL DEFAULT '',
    goal TEXT NOT NULL DEFAULT ''
);