/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Event from './Event';
import Location from './Location';
import UserMinimal from './UserMinimal';
import Volounteers from './Volounteers';

/**
 * The EventForOrg model module.
 * @module model/EventForOrg
 * @version 1.0.0
 */
export default class EventForOrg extends Event {
  /**
   * Constructs a new <code>EventForOrg</code>.
   * Event with addtional information for event coordinators.
   * @alias module:model/EventForOrg
   * @class
   * @extends module:model/Event
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>EventForOrg</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventForOrg} obj Optional instance to populate.
   * @return {module:model/EventForOrg} The populated <code>EventForOrg</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventForOrg();
      Event.constructFromObject(data, obj);
      if (data.hasOwnProperty('volounteers'))
        obj.volounteers = ApiClient.convertToType(data['volounteers'], [UserMinimal]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/UserMinimal>} volounteers
 */
EventForOrg.prototype.volounteers = undefined;

