/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The EventidUsersBody model module.
 * @module model/EventidUsersBody
 * @version 1.0.0
 */
export default class EventidUsersBody {
  /**
   * Constructs a new <code>EventidUsersBody</code>.
   * @alias module:model/EventidUsersBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EventidUsersBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventidUsersBody} obj Optional instance to populate.
   * @return {module:model/EventidUsersBody} The populated <code>EventidUsersBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventidUsersBody();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
EventidUsersBody.prototype.userId = undefined;

