/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Location from './Location';

/**
 * The Event model module.
 * @module model/Event
 * @version 1.0.0
 */
export default class Event {
  /**
   * Constructs a new <code>Event</code>.
   * @alias module:model/Event
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Event} obj Optional instance to populate.
   * @return {module:model/Event} The populated <code>Event</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Event();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = Location.constructFromObject(data['location']);
      if (data.hasOwnProperty('organisationId'))
        obj.organisationId = ApiClient.convertToType(data['organisationId'], 'String');
      if (data.hasOwnProperty('imageUrls'))
        obj.imageUrls = ApiClient.convertToType(data['imageUrls'], ['String']);
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Event.prototype.id = undefined;

/**
 * @member {String} title
 */
Event.prototype.title = undefined;

/**
 * @member {String} description
 */
Event.prototype.description = undefined;

/**
 * @member {module:model/Location} location
 */
Event.prototype.location = undefined;

/**
 * @member {String} organisationId
 */
Event.prototype.organisationId = undefined;

/**
 * @member {Array.<String>} imageUrls
 */
Event.prototype.imageUrls = undefined;

/**
 * @member {Date} startDate
 */
Event.prototype.startDate = undefined;

/**
 * @member {Date} endDate
 */
Event.prototype.endDate = undefined;

