/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The EventidTopicsBody model module.
 * @module model/EventidTopicsBody
 * @version 1.0.0
 */
export default class EventidTopicsBody {
  /**
   * Constructs a new <code>EventidTopicsBody</code>.
   * @alias module:model/EventidTopicsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EventidTopicsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventidTopicsBody} obj Optional instance to populate.
   * @return {module:model/EventidTopicsBody} The populated <code>EventidTopicsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventidTopicsBody();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
EventidTopicsBody.prototype.title = undefined;

/**
 * @member {String} description
 */
EventidTopicsBody.prototype.description = undefined;

