/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Location model module.
 * @module model/Location
 * @version 1.0.0
 */
export default class Location {
  /**
   * Constructs a new <code>Location</code>.
   * @alias module:model/Location
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Location</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Location} obj Optional instance to populate.
   * @return {module:model/Location} The populated <code>Location</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Location();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('coordinates'))
        obj.coordinates = ApiClient.convertToType(data['coordinates'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Location.prototype.id = undefined;

/**
 * @member {String} name
 */
Location.prototype.name = undefined;

/**
 * @member {String} coordinates
 */
Location.prototype.coordinates = undefined;

