/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Organisation model module.
 * @module model/Organisation
 * @version 1.0.0
 */
export default class Organisation {
  /**
   * Constructs a new <code>Organisation</code>.
   * @alias module:model/Organisation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Organisation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Organisation} obj Optional instance to populate.
   * @return {module:model/Organisation} The populated <code>Organisation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Organisation();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('imageUrls'))
        obj.imageUrls = ApiClient.convertToType(data['imageUrls'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Organisation.prototype.id = undefined;

/**
 * @member {String} name
 */
Organisation.prototype.name = undefined;

/**
 * @member {String} description
 */
Organisation.prototype.description = undefined;

/**
 * @member {Array.<String>} imageUrls
 */
Organisation.prototype.imageUrls = undefined;

