/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrgParticipant model module.
 * @module model/OrgParticipant
 * @version 1.0.0
 */
export default class OrgParticipant {
  /**
   * Constructs a new <code>OrgParticipant</code>.
   * @alias module:model/OrgParticipant
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrgParticipant</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrgParticipant} obj Optional instance to populate.
   * @return {module:model/OrgParticipant} The populated <code>OrgParticipant</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrgParticipant();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('orgId'))
        obj.orgId = ApiClient.convertToType(data['orgId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
OrgParticipant.prototype.type = undefined;

/**
 * @member {String} orgId
 */
OrgParticipant.prototype.orgId = undefined;

