/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Task model module.
 * @module model/Task
 * @version 1.0.0
 */
export default class Task {
  /**
   * Constructs a new <code>Task</code>.
   * @alias module:model/Task
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Task</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Task} obj Optional instance to populate.
   * @return {module:model/Task} The populated <code>Task</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Task();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('learningGoal'))
        obj.learningGoal = ApiClient.convertToType(data['learningGoal'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Task.prototype.id = undefined;

/**
 * @member {String} description
 */
Task.prototype.description = undefined;

/**
 * @member {String} learningGoal
 */
Task.prototype.learningGoal = undefined;

/**
 * @member {Array.<String>} tags
 */
Task.prototype.tags = undefined;

