/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Topic model module.
 * @module model/Topic
 * @version 1.0.0
 */
export default class Topic {
  /**
   * Constructs a new <code>Topic</code>.
   * @alias module:model/Topic
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Topic</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Topic} obj Optional instance to populate.
   * @return {module:model/Topic} The populated <code>Topic</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Topic();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('creator'))
        obj.creator = ApiClient.convertToType(data['creator'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('lastUpdate'))
        obj.lastUpdate = ApiClient.convertToType(data['lastUpdate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Topic.prototype.id = undefined;

/**
 * @member {String} title
 */
Topic.prototype.title = undefined;

/**
 * @member {String} description
 */
Topic.prototype.description = undefined;

/**
 * @member {String} creator
 */
Topic.prototype.creator = undefined;

/**
 * @member {Date} created
 */
Topic.prototype.created = undefined;

/**
 * @member {Date} lastUpdate
 */
Topic.prototype.lastUpdate = undefined;

