/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import OrgParticipant from './OrgParticipant';
import UserMinimal from './UserMinimal';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
export default class User extends UserMinimal {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   * @extends module:model/UserMinimal
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      UserMinimal.constructFromObject(data, obj);
      if (data.hasOwnProperty('orgs'))
        obj.orgs = ApiClient.convertToType(data['orgs'], [OrgParticipant]);
      if (data.hasOwnProperty('pastEvents'))
        obj.pastEvents = ApiClient.convertToType(data['pastEvents'], [Object]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/OrgParticipant>} orgs
 */
User.prototype.orgs = undefined;

/**
 * @member {Array.<Object>} pastEvents
 */
User.prototype.pastEvents = undefined;

