/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserMin model module.
 * @module model/UserMin
 * @version 1.0.0
 */
export default class UserMin {
  /**
   * Constructs a new <code>UserMin</code>.
   * @alias module:model/UserMin
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserMin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserMin} obj Optional instance to populate.
   * @return {module:model/UserMin} The populated <code>UserMin</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserMin();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UserMin.prototype.id = undefined;

/**
 * @member {String} displayName
 */
UserMin.prototype.displayName = undefined;

