/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import UserMinimal from './UserMinimal';

/**
 * The Volounteers model module.
 * @module model/Volounteers
 * @version 1.0.0
 */
export default class Volounteers {
  /**
   * Constructs a new <code>Volounteers</code>.
   * @alias module:model/Volounteers
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Volounteers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Volounteers} obj Optional instance to populate.
   * @return {module:model/Volounteers} The populated <code>Volounteers</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Volounteers();
      if (data.hasOwnProperty('volounteers'))
        obj.volounteers = ApiClient.convertToType(data['volounteers'], [UserMinimal]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/UserMinimal>} volounteers
 */
Volounteers.prototype.volounteers = undefined;

