/*
 * Wolontariusz API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.73
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WolontariuszApi);
  }
}(this, function(expect, WolontariuszApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Volounteers', function() {
      beforeEach(function() {
        instance = new WolontariuszApi.Volounteers();
      });

      it('should create an instance of Volounteers', function() {
        // TODO: update the code to test Volounteers
        expect(instance).to.be.a(WolontariuszApi.Volounteers);
      });

      it('should have the property volounteers (base name: "volounteers")', function() {
        // TODO: update the code to test the property volounteers
        expect(instance).to.have.property('volounteers');
        // expect(instance.volounteers).to.be(expectedValueLiteral);
      });

    });
  });

}));
